# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "kartverket.dev"
  tags:
  - "internal"
spec:
  type: "website"
  lifecycle: "production"
  owner: "skip"
  providesApis:
  - "kartverket.dev-api"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Group"
metadata:
  name: "security_champion_kartverket.dev"
  title: "Security Champion kartverket.dev"
spec:
  type: "security_champion"
  parent: "it_security_champions"
  members:
  - "eliihen"
  children:
  - "resource:kartverket.dev"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "kartverket.dev"
  links:
  - url: "https://github.com/kartverket/kartverket.dev"
    title: "kartverket.dev på GitHub"
spec:
  type: "repo"
  owner: "security_champion_kartverket.dev"
  dependencyOf:
  - "component:kartverket.dev"
---
apiVersion: "backstage.io/v1alpha1"
kind: "API"
metadata:
  name: "kartverket.dev-api"
  tags:
  - "internal"
spec:
  type: "openapi"
  lifecycle: "production"
  owner: "skip"
  definition: |
    openapi: "3.0.0"
    info:
        title: kartverket.dev API
    paths:
