apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kartverket.dev
  tags:
    - internal
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: skvis
  system: system:default/utviklerportal
