apiVersion: kartverket.dev/v1alpha1
kind: Function
metadata:
  name: eiendom-funksjon
  description: Tester funksjon
spec:
  owner: skvis
  childFunctions: [kart-funksjon, tinglysning-funksjon]
---
apiVersion: kartverket.dev/v1alpha1
kind: Function
metadata:
  name: kart-funksjon
  description: Tester funksjon
spec:
  owner: skvis
  childSystems: [funksjon-skjema-register]
---
apiVersion: kartverket.dev/v1alpha1
kind: Function
metadata:
  name: tinglysning-funksjon
  description: Tester funksjon
spec:
  owner: skvis
  childSystems: [norgeskart]
