apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sjokoladerute-api
  title: API for sjokoladeruter
  description: Autoritativt syntetisk API for grenser mellom spiselige eiendommer
spec:
  type: openapi
  lifecycle: experimental
  owner: lag-knekk
  system: sjokoladematrikkelen
  definition: |
    openapi: 3.0.3
    info:
      title: API for sjokoladeruter
      version: 1.0.0
    paths:
      /sjokoladeruter:
        get:
          responses:
            '200':
              description: En autoritativ liste over sjokoladeruter
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: siste-bit-sok-api
  title: API for Siste bit-søket
  description: Syntetisk API for å finne bortkommet godteri på tvers av systemer
spec:
  type: openapi
  lifecycle: experimental
  owner: lag-seig
  system: siste-bit-soket
  definition: |
    openapi: 3.0.3
    info:
      title: API for Siste bit-søket
      version: 1.0.0
    paths:
      /savnede-biter:
        get:
          responses:
            '200':
              description: Mulige steder den savnede favorittbiten kan befinne seg
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sjokoladeregisteret
  title: Sjokoladeregisteret
  description: Minneregister over sjokoladeruter, knekkgrenser og eierskap
spec:
  type: database
  owner: lag-knekk
  system: sjokoladematrikkelen
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: blandingsposeindeksen
  title: Blandingsposeindeksen
  description: Søkeindeks over alle kjente biter i lørdagsgodtposen
spec:
  type: search-index
  owner: lag-seig
  system: siste-bit-soket
