apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: godteriverkets-lokale-katalog
  description: Godteriverkets syntetiske katalog for lokal utvikling uten eksterne tilganger
spec:
  type: file
  targets:
    - ./organization.yaml
    - ./domains-and-systems.yaml
    - ./components.yaml
    - ./apis-and-resources.yaml
    - ./functions.yaml
